[project]
name = "python-face-cropper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "numpy>=2.3.0",
    "opencv-python>=4.11.0.86",
    "tqdm>=4.67.1",
]
